# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ticket_service_pb2 as ticket__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ticket_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketClientServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ticketservice.v1.TicketClientService/Login',
                request_serializer=ticket__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/ticketservice.v1.TicketClientService/Logout',
                request_serializer=ticket__service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Post = channel.unary_unary(
                '/ticketservice.v1.TicketClientService/Post',
                request_serializer=ticket__service__pb2.PostRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/ticketservice.v1.TicketClientService/Get',
                request_serializer=ticket__service__pb2.GetRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.GetResponse.FromString,
                _registered_method=True)


class TicketClientServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ticket__service__pb2.LoginRequest.FromString,
                    response_serializer=ticket__service__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=ticket__service__pb2.LogoutRequest.FromString,
                    response_serializer=ticket__service__pb2.StatusResponse.SerializeToString,
            ),
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=ticket__service__pb2.PostRequest.FromString,
                    response_serializer=ticket__service__pb2.StatusResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=ticket__service__pb2.GetRequest.FromString,
                    response_serializer=ticket__service__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticketservice.v1.TicketClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticketservice.v1.TicketClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketClientService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketClientService/Login',
            ticket__service__pb2.LoginRequest.SerializeToString,
            ticket__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketClientService/Logout',
            ticket__service__pb2.LogoutRequest.SerializeToString,
            ticket__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketClientService/Post',
            ticket__service__pb2.PostRequest.SerializeToString,
            ticket__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketClientService/Get',
            ticket__service__pb2.GetRequest.SerializeToString,
            ticket__service__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TicketAppServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessBusinessRequest = channel.unary_unary(
                '/ticketservice.v1.TicketAppService/ProcessBusinessRequest',
                request_serializer=ticket__service__pb2.BusinessRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetLLMAnswer = channel.unary_unary(
                '/ticketservice.v1.TicketAppService/GetLLMAnswer',
                request_serializer=ticket__service__pb2.LLMQueryRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.GetLLMAnswerResponse.FromString,
                _registered_method=True)


class TicketAppServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessBusinessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLLMAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessBusinessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBusinessRequest,
                    request_deserializer=ticket__service__pb2.BusinessRequest.FromString,
                    response_serializer=ticket__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetLLMAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLLMAnswer,
                    request_deserializer=ticket__service__pb2.LLMQueryRequest.FromString,
                    response_serializer=ticket__service__pb2.GetLLMAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticketservice.v1.TicketAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticketservice.v1.TicketAppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketAppService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessBusinessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketAppService/ProcessBusinessRequest',
            ticket__service__pb2.BusinessRequest.SerializeToString,
            ticket__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLLMAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.TicketAppService/GetLLMAnswer',
            ticket__service__pb2.LLMQueryRequest.SerializeToString,
            ticket__service__pb2.GetLLMAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLLMAnswer = channel.unary_unary(
                '/ticketservice.v1.LLMService/GetLLMAnswer',
                request_serializer=ticket__service__pb2.LLMQueryRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.GetLLMAnswerResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetLLMAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLLMAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLLMAnswer,
                    request_deserializer=ticket__service__pb2.LLMQueryRequest.FromString,
                    response_serializer=ticket__service__pb2.GetLLMAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticketservice.v1.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticketservice.v1.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLLMAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticketservice.v1.LLMService/GetLLMAnswer',
            ticket__service__pb2.LLMQueryRequest.SerializeToString,
            ticket__service__pb2.GetLLMAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
